### PR TITLE
YangType.Equal should check whether inputs are nil

### LINKED ISSUE #178: YangType.Equal should check whether inputs are nil
Since it doesn't, it causes a nil pointer exception when inputs are nil.

### PR DESCRIPTION
**Pull request by wenovus**
Fixed #178

### CODE REVIEW

File: pkg/yang/yangtype_test.go [hunk 1]
```diff
@@ -0,0 +1,53 @@
...
+			Name:           "foo",
+			Kind:           Ydecimal64,
+			FractionDigits: 5,
+		},
+		inRight: &YangType{
+			Name:           "bar",
+			Kind:           Ydecimal64,
+			FractionDigits: 5,
+		},
+		wantEqual: true,
```
Comment (robshakir) [inline pkg/yang/yangtype_test.go:39]: Test the unequal case where they're the same name but different types?

**Review by robshakir — APPROVED** [review]

File: pkg/yang/yangtype_test.go (hunk 1 above)
Comment (wenovus) [reply pkg/yang/yangtype_test.go:53]: Done.
